### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by craigneasbey** [craigneasbey/Biblecast#12]
While adding espresso tests with the androidTest build variant, I came across this error when running via USB on a Google Nexus 4:

```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
at au.id.neasbey.biblecast.BibleSearch.onCreate(BibleSearch.java:99)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:494)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)


java.lang.RuntimeException: Unable to start activity ComponentInfo{au.id.neasbey.biblecast/au.id.neasbey.biblecast.BibleSearch}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
at android.app.ActivityThread.access$800(ActivityThread.java:151)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
at au.id.neasbey.biblecast.BibleSearch.onCreate(BibleSearch.java:99)
at android.app.Activity.performCreate(Activity.java:5990)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:494)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
... 10 more

Test running failed: Instrumentation run failed due to 'java.lang.IllegalStateException'
```

**Comment by craigneasbey** [comment]
After spending days on this issue, I found a solution for my symptoms.  It appears many people are having the issue with different root causes.  Many people had this issue: http://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity
This is the issue that worked for me: http://stackoverflow.com/questions/28570785/material-design-support-below-lollipop-crashes

Changes
- theme name from "AppTheme" to "MyAppTheme"
- upgraded the libraries:
  - com.android.tools.build:gradle:2.0.0-beta5
  - distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip
  - com.android.support:appcompat-v7:23.1.1
- import android.support.v7.app.AlertDialog

**Comment by yemresaglam** [comment]
If you add the `android:theme="@style/Theme.AppCompat.Light"` to `<application>` in AndroidManifest.xml file, problem is solving.

**Comment by HishamSn** [comment]
thank u a lot 👍
